### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by halx99** [adxeproject/adxe#1]
## Notes
  - Other performance topic: https://forum.cocos.org/t/topic/90248, showcase: http://www.icarus-li.com/video/d1.mp4
  - ProgramState not cache, v3 cached, my cause some compatible issue
  - At cocos2d-x-v4,  the ProgramState could shared only object have same texture, such as
   ```cpp

ProgramState* ProgramStateRegistry::getProgramState(ProgramType programType, Texture2D* texture)
{
    auto textureFormatEXT = texture ? texture->getTextureFormatEXT() : 0;
    
    char hashMe[sizeof(programType) + sizeof(texture)];
    memcpy(hashMe, &programType, sizeof(programType));
    memcpy(hashMe + sizeof(programType), &texture, sizeof(texture));
    auto key = XXH32((const void*)&hashMe, sizeof(hashMe), 0);

    auto iter = _programStateCache.find(key);
    if (iter != _programStateCache.end())
        return iter->second;

    auto programState = newProgramState(programType, textureFormatEXT);
    if (programState) {
        _programStateCache.emplace(key, programState);
    }
    return programState;
}
   ```
## Engine core
  - [x] RenderTarget abstract
  - [x] Refactor enums map method, use table instead many much switch case
  - [x] Cache depthstencil state, tsl::robin_map
  - [x] Remove ```FileUtils::getFileDataFromZip```, recommend use ```ZipFile``` instead
  - [x] ASTC 4x4/8x8 support
  - [x] ETC2 RGB/RGBA support
  - [x] Improve Image, fast forward ```compression texels data``` to GPU
  - [x] Refactor audio engine, OpenAL for all platforms
  - [x] Remove SimpleAudio
  - [ ] Remove offthread file operation
  - [x] Explicit convert utf-8 file path to wide-string and call wide win32 file operation APIs
  - [x] Refactor Downloader, curl for all platforms, don't use scheduler to retrieve progress info, make it more reusable
  - [x] minizip-1.2.0
  - [x] ccMessageBox
  - [x] BMP support with stb_image
  - [x] Remove unused libuv
  - [ ] Reorder child support
  - [x] Remove tinyxml2 dep, use pugixml instead
  - [x] Use xsxml for SAX parser only
  - [x] Multi meta textures v1.0
  - [x] ProgramStateRegistry
  - [x] ANGLE support.
  - [x] Use curl for HttpClient all platforms
  - [x] Remove xxtea
  - [x] Remove rapidxml dep
  - [x] Fix etc1 alpha test case, content size incorrect
  - [x] Remove fmod for linux
  - [x] Use stat to check regular file exist for android platform
  - [x] Use int64_t as return type for getFileSize
  - [x] ios .ogg support
  - [x] ZipUtils streaming API, support streaming play audio file in android obb
  - [x] Add & Improve play .wav audio at all platforms
  - [x] Remove unnecessary workaround to process audio tail frame at non-apple platforms.
  - [ ] Cache ProgramState
  - [x] Remove socket.io websockets, use yasio for socket connection solution
  - [x] Fully streaming play for all media file: .mp4, .mp3, .ogg, .wav
  - [x] Streaming load for .ttf with freetype2
  - [x] Remove CCB(already removed in v4)
  - [ ] Purely offthread load texture, use shared gl context
  - [x] Refactor UserDefault with file mapping io with encrypt support
  - [ ] msaa
  - [ ] Refactor VideoPlayer
  - [ ] GPU texture array support
  - [ ] OpenGL RenderBuffer for depth stencil buffer D24S8

## Thirdparty
  - [x] Use git submodules to manage 3rd libs or marge 3rd repo to main repo  
  - [x] Update zlib to 1.2.11  

## Extensions:
  - [x] move spine, ccs, dragonBones to extensions
  - [x] All extensions should be optional and can disable relax
  - [x] ImGuiEXT
  - [x] FairyGUI
  - [x] spine-3.8
  - [x] cocostudio
  - [x] dragonBones
  - [x] Also move lua binding to extension
  - [x] Also move spine-cpp to extension
  - [ ] EncryptSystem
  - [ ] particle system: https://github.com/effekseer
 
## Toolsets And build env
- [x] Use system env for cmake to avoid copy engine sources when create new project
- [x] lua-template and lua-empty-test needs fix
- [ ] New command line tool
- [ ] GUI Peoject Creator
- [ ] Sence Editor with ImGui

## Lua Binding
  - [x] Lua53 compat
  - [x] Use plainlua instead luajit
  - [x] make lua test works well
  - [x] Remvoe luasocket, use yasio for socket connection solution
  - [ ] Use sol2 for binding framework instead tolua++

## poors of LuaJIT
  - Lack of maintain
  - High crash from game developer
  - Hard to unify bytecode run on 32/64 with same bytecode
  - Performance slow than ```planlua``` without restricts programing (luajit have to many programing restricts)

## benefit of lua5.4
- compat bytecode 32,64bit app without any changes

**Comment by imtrobin** [comment]
Can you provide the dependencies source too, so we can also compile them.

**Comment by halx99** [comment]
I will provide later

**Comment by halx99** [comment]
@imtrobin ok done deps for win32, now you can do follow steps to run cpp-tests on win32
```bat
python download-deps.py
mkdir build
cd build
cmake -A Win32 ..
```
After vsproject generated, just open Cocos2d-x.sln to build cpp-tests and run it.

**Comment by weiwest** [comment]
Auto choice best renderer from multi backends.

**Comment by halx99** [comment]
android {
    aaptOptions {
       noCompress 'mp3','ogg','wav','mp4','ttf'
    }
}

**Comment by stevetranby** [comment]
Note: OpenAL is deprecated on macOS 10.15.6 and 11 (10.16).
"The OpenAL framework is deprecated and remains present for compatibility purposes. Transition to AVAudioEngine for spatial audio functionality."

**Comment by halx99** [comment]
engine-x already adapte openal-soft on ios

**Comment by halx99** [comment]
Refactor AudioEngine, OpenAL for all platforms, and on iOS, can switch to openal-soft through -DCC_USE_ALSOFT_ON_APPLE since Apple mark OpenAL framework deprecated on iOS12

**Comment by halx99** [comment]
TODO: manually
add line spacing support for system font on iOS and Android
https://github.com/cocos2d/cocos2d-x/commit/89e75eec084ac5d179040bd1c88ca8692b352d8c

TODO: manullay
[iOS]Screen Time would makes App stuck sometimes
https://github.com/cocos2d/cocos2d-x/commit/ef16d4f24463582cdad268e659b00d730c0abca4

TODO: manually
Bug?, use fastest_csv_parser/fast_split instead
https://github.com/cocos2d/cocos2d-x/pull/20483

manually
Added tmx animated tile support, with test case [done]

checked
don't set glview transparent, it many cause afterimage (#20298) [yes]

V4 Good PR: https://github.com/cocos2d/cocos2d-x/pull/20506

**Comment by halx99** [comment]
Imgui hdpi support:
## Simple on windows
```cpp
    /*
    * config high dpi scaling
    */
#define IMGUI_SCALE_FACTOR 1.2f
#define IMGUI_DEFAULT_FONT_SIZE 13.0f

    HDC hdc = GetWindowDC(nullptr);
    int xpixels = GetDeviceCaps(hdc, LOGPIXELSX);
    ReleaseDC(nullptr, hdc);

    float dpiScale = (float)xpixels / (float)USER_DEFAULT_SCREEN_DPI;
    auto finalScale = IMGUI_SCALE_FACTOR * dpiScale;

    auto imFonts = ImGui::GetIO().Fonts;
    auto imChars = imFonts->GetGlyphRangesChineseSimplifiedCommon();
    // auto imAllChars = imFonts->GetGlyphRangesChineseFull();
    imFonts->AddFontFromFileTTF(R"(C:\Windows\Fonts\msyh.ttc)", IMGUI_DEFAULT_FONT_SIZE * IMGUI_SCALE_FACTOR, nullptr, imChars);
    
    ImGui::GetStyle().ScaleAllSizes(IMGUI_SCALE_FACTOR);
```
## Other references:
https://github.com/ocornut/imgui/pull/2826
https://doc.magnum.graphics/magnum/classMagnum_1_1ImGuiIntegration_1_1Context.html

**Comment by balancedwolf** [comment]
I've opened a pull request for multi textured layers, can be a very high arbitrary number of textures with opengl but metal is in the middle of the problem
